# Generated by Django 5.1 on 2024-12-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0002_task_assignee_alter_task_checklists_alter_task_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="current_group_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("assignee", "Assignee"),
                    ("priority", "Priority"),
                    ("sprint", "Sprint"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
