# Generated by Django 5.1 on 2024-12-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0003_board_current_group_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="current_group_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("assignee", "Assignee"),
                    ("priority", "Priority"),
                    ("sprint", "Sprint"),
                    ("task_type", "Task Type"),
                    ("estimate", "Estimate"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
