# Generated by Django 5.1 on 2025-01-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0004_alter_board_current_group_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="github_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="google_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
