# Generated by Django 5.1 on 2025-01-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0005_user_github_id_user_google_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="github_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="google_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
