# Generated by Django 5.1 on 2025-01-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0007_document_block_documentteampermission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="category",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                ],
                default="open",
                max_length=24,
            ),
        ),
    ]
