# Generated by Django 5.1 on 2025-01-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0008_state_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
