# Generated by Django 5.1 on 2025-01-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calyvim",
            "0010_documentpermission_role_documentteampermission_role_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="block_type",
            field=models.CharField(
                choices=[
                    ("heading_1", "Heading 1"),
                    ("heading_2", "Heading 2"),
                    ("heading_3", "Heading 3"),
                    ("paragraph", "Paragraph"),
                    ("quote", "Quote"),
                    ("toggle", "Toggle"),
                    ("bullet_list", "Bullet List"),
                    ("numbered_list", "Numbered List"),
                    ("code", "Code"),
                    ("link", "Link"),
                    ("page", "Page"),
                ],
                default="paragraph",
                max_length=24,
            ),
        ),
    ]
