# Generated by Django 5.1 on 2025-01-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0011_alter_block_block_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="block",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
