# Generated by Django 5.1 on 2025-01-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0012_block_archived_at_block_is_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="description_raw",
            field=models.TextField(blank=True, null=True),
        ),
    ]
