# Generated by Django 5.1 on 2025-01-18 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0017_tasksnapshot"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TaskStateLog",
        ),
    ]
