# Generated by Django 5.1 on 2025-01-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0018_delete_taskstatelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="code",
            field=models.CharField(
                blank=True, editable=False, max_length=10, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="board-covers/"),
        ),
        migrations.AlterField(
            model_name="board",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="board-logos/"),
        ),
        migrations.AlterField(
            model_name="taskattachment",
            name="attachment",
            field=models.FileField(upload_to="task-attachments/"),
        ),
        migrations.AlterField(
            model_name="team",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="team-avatars/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="user-avatars/"),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
    ]
