# Generated by Django 5.1 on 2025-01-21 12:06

from django.db import migrations
from django.utils.crypto import get_random_string


def prefill_workspace_code(apps, schema_editor):
    Workspace = apps.get_model("calyvim", "Workspace")
    for workspace in Workspace.objects.all():
        if not workspace.code:
            workspace.code = get_random_string(6).upper()
            workspace.save(update_fields=["code"])


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0019_workspace_code_alter_board_cover_alter_board_logo_and_more"),
    ]

    operations = [
        migrations.RunPython(
            prefill_workspace_code, reverse_code=migrations.RunPython.noop
        ),
    ]
