# Generated by Django 5.1 on 2025-01-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0021_remove_sprint_unique_active_sprint_per_board_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="color",
            field=models.CharField(default="#7D52E9", max_length=10),
        ),
    ]
