# Generated by Django 5.1 on 2025-01-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0022_alter_label_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
